env:
  matrix:
  - MRUBY_REPO=https://github.com/mruby/mruby.git MRUBY_BRANCH=master
  - MRUBY_REPO=https://bitbucket.org/monami_ya_mrb/monami-ya.mrb.git MRUBY_BRANCH=master
  - MRUBY_REPO=https://bitbucket.org/monami_ya_mrb/monami-ya.mrb.git MRUBY_BRANCH=develop
script:
- ruby run_test.rb all test
branches:
  only:
  - master
notifications:
  hipchat:
    rooms:
      secure: SgQq3nHixOiCOmyBOCkNqOOZmwrxrojvj/M77An+njfesP9+UlsNs+hif2/JqLleH0h7WhEsRArHr3bHwyjb6HgES6BUfeNcHkaoFCCjM03x9ajwXm2QmbhUkIMAtIngjb6DblncgGi9cbMsGlAJe+6KTadhGjpRBwzhw1NyMFs=
